# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa9d28f86729430b67f22df5997ae19516873f29b5458ff1d1adab4f5a748ad00a7c3f0823b865283bb687c9ef6954b9dbb2e09106b5556dbcc420624d1790f

test:
  secret_key_base: 3f3f091bf7c67ed4fc2e71d469fe2b89b23213af8c8d8491973823914d9ac3fea4229c6283f7af186e9114a3ea76c9f053e919b464c4db515194eee3c2f69039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
